
steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/resepku-frontend', '.']

  # Step 2: Push image ke Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/resepku-frontend']

  # Step 3: Deploy ke Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'resepku-frontend' # Ganti dengan nama service Cloud Run kamu
      - '--image=gcr.io/$PROJECT_ID/resepku-frontend'
      - '--platform=managed'
      - '--region=us-central1' # Ganti dengan region sesuai kebutuhan
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/resepku-frontend'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1600s" 